my_entity.smile_test_type.*:
  type: config_entity
  label: 'Smile test type config'
  mapping:
    id:
      type: integer
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: string
      label: 'Name'
    preferred_brand:
        type: select
        label: 'Brand field'
    products_owned_count:
      type: integer
      label: 'Products count'
    user_id:
      type: entity_reference
      label: 'User Name'
